name: jaspr_web
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.8

dependencies:
  jaspr: ^0.22.3
  shared_core:
    path: ../../packages/shared_core

dev_dependencies:
  lints: ^6.1.0
  jaspr_builder: ^0.22.3
  build_runner: ^2.11.1
